name: Continuous integration
on:
  push:
    branches:
      - dev
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache PlatformIO packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run cpp check
        run: pio check

      - name: Build unit tests
        run: pio test

      - name: Build code
        run: pio run -e uno
